---
- name: install_apache
  yum: name='httpd' state='present'

- name: install_xinetd
  yum: name='xinetd' state='present'

- name: install_tftp-server
  yum: name='tftp-server' state='present'

- name: configure_tftp
  lineinfile: dest=/etc/xinetd.d/tftp regexp="disable" line="        disable                 = no"

- name: copy_ipxe_chainboot
  copy: src=undionly.kkpxe dest=/var/lib/tftpboot/undionly.kkpxe owner=root group=root mode="0644"

- name: copy_ipxe_chainboot
  copy: src=undionly.kpxe dest=/var/lib/tftpboot/undionly.kpxe owner=root group=root mode="0644"

- name: copy_uefi_chainboot
  copy: src=ipxe-x86.efi dest=/var/lib/tftpboot/ipxe-x86.efi owner=root group=root mode="0644"

- name: ipxe_selinux_context
  command: restorecon -Rv /var/lib/tftpboot/

- name: copy_pxe_bootscript
  copy: src=boot.py dest=/var/www/cgi-bin/boot.py owner=apache group=apache mode="0550"

- name: create_ks_dir
  file: path=/var/www/html/ks state=directory owner=apache group=apache mode="0755"

- name: download PXE initrd.img file
  get_url: url="{{ repo_location}}/images/pxeboot/initrd.img" dest=/var/www/html/ks/initrd.img force=yes owner=apache group=apache mode="0550"

- name: download PXE vmlinuz file
  get_url: url="{{ repo_location}}/images/pxeboot/vmlinuz" dest=/var/www/html/ks/vmlinuz force=yes owner=apache group=apache mode="0550"

- name: download PXE upgrade.img file
  get_url: url="{{ repo_location}}/images/pxeboot/upgrade.img" dest=/var/www/html/ks/initrd.img force=yes owner=apache group=apache mode="0550"

- name: create_dhcpd_config_dir
  file: path=/etc/dhcp/dhcpd.d state=directory owner=root group=root mode="0755"

- name: copy_dhcp_pxe_option_config
  copy: src=ipxe.conf dest=/etc/dhcp/dhcpd.d/ipxe.conf owner=root group=root mode="0644"

- name: create_pxe_directory_structure
  file: path=/var/www/provision state=directory owner=root group=root mode="0755"

- name: create_pxe_directory_structure
  file: path=/var/www/provision/nodes state=directory owner=apache group=apache mode="0755"

- name: create_pxe_directory_structure
  file: path=/var/www/provision/reinstall state=directory owner=apache group=apache mode="0755"

- name: apache_selinux_context
  command: restorecon -Rv /var/www/provision/

- name: start and enable httpd service
  service: name=httpd state=started enabled=yes

- name: start and enable xinetd service
  service: name=xinetd state=started enabled=yes

